nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: |
                API REST pour la consultation des produits BileMo et gestion des utilisateurs clients.

                ## Authentification
                Toutes les routes (sauf /api/auth/login) nécessitent un token JWT valide dans l'en-tête Authorization:
                `Authorization: Bearer {votre_token}`
            version: 1.0.0
            contact:
                name: Support BileMo
                email: support@bilemo.com
        servers:
            - url: 'https://localhost:8000'
              description: Development server
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: Token JWT obtenu via /api/auth/login
            schemas:
                Error:
                    type: object
                    properties:
                        error:
                            type: string
                            description: Message d'erreur
                            example: "Resource not found"
                PaginationLinks:
                    type: object
                    properties:
                        self:
                            type: object
                            properties:
                                href:
                                    type: string
                                    example: "/api/products?page=2"
                        first:
                            type: object
                            properties:
                                href:
                                    type: string
                                    example: "/api/products?page=1"
                        last:
                            type: object
                            properties:
                                href:
                                    type: string
                                    example: "/api/products?page=10"
                        prev:
                            type: object
                            properties:
                                href:
                                    type: string
                                    example: "/api/products?page=1"
                        next:
                            type: object
                            properties:
                                href:
                                    type: string
                                    example: "/api/products?page=3"
    areas:
        path_patterns:
            - ^/api(?!/doc$)

